import type { Metadata } from "next";
import "./globals.css";
import { DashboardLayout } from "./components/layout/DashboardLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="vi">
      <body>
        <DashboardLayout />

        {children}
      </body>
    </html>
  );
}
