import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "./components/layout/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="vi">
      <body>
        <Layout />

        <div className="absolute top-[70px] lg:left-[240px] left-0 lg:w-[calc(100%-240px)] w-full min-h-[calc(100vh-70px)] bg-[#F4F5F9] py-[30px] sm:px-[30px] px-[15px]">
          {children}
        </div>

      </body>
    </html>
  );
}
