server:
  port: 8080
  servlet:
    context-path: /shopco

spring:
  application:
    name: shopco
  datasource:
    url: "jdbc:mysql://localhost:3306/shopco"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true